version: '2'

services:
  postgres:
    build: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - ./postgres/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  webapp:
    build: webapp
    ports:
      - "8289:8289"
    environment:
      - HTTP_PORT=8289
      - DATABASE_URL=postgres://webapp:eventmAnager@!$$@postgres/eventmanager
    links:
      - postgres:postgres
    volumes:
      - ./webapp/views:/usr/src/app/views

volumes:
  postgres-data:
    driver: local